services:

  # ─── PostgreSQL ───────────────────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: pg_main
    restart: unless-stopped
    environment:
      POSTGRES_USER:     ${POSTGRES_USER:-postgres} # по умолчанию postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}   # по умолчанию postgres
      POSTGRES_DB:       ${POSTGRES_DB:-app_db}
      PGDATA:            /var/lib/postgresql/data/pgdata # Путь внутри контейнера, где PostgreSQL хранит свои данные.
    volumes:
      - pg_data:/var/lib/postgresql/data #
      - ./init-scripts:/docker-entrypoint-initdb.d:ro  # SQL/sh скрипты при первом запуске
    ports:
      - "127.0.0.1:5432:5432"   # только localhost — не выставлять в 0.0.0.0 на prod
    networks:
      - pg_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-app_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ─── pgAdmin 4 ────────────────────────────────────────
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL:    ${PGADMIN_EMAIL:-admin@local.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-postgres}
      PGADMIN_CONFIG_SERVER_MODE: "False"       # single-user режим (dev)
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro  # автоподключение к БД
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - pg_net
    depends_on:
      postgres:
        condition: service_healthy

# ─── Volumes ──────────────────────────────────────────
volumes:
  pg_data:
    name: pg_data # видеть предсказуемое имя в docker volume ls
  pgadmin_data:
    name: pgadmin_data

# ─── Networks ─────────────────────────────────────────
networks:
  pg_net:
    name: pg_net # контейнеры в одной сети могут обращаться друг к другу по имени сервиса
    driver: bridge # контейнеры живут в изолированной виртуальной сети